### ISSUE TITLE
Any documentation around?

### ISSUE THREAD

**Issue by vhugogarcia** [alexrainman/Xamarin.Forms.PDFViewer#1]
Hello friend,

Thanks for bringing this awesome library.

Would you mind share some information about how to use it in a Xamarin.forms project?

thank you.

**Comment by alexrainman** [comment]
Hi, sorry for not answering this a long time ago. If you need any support let me know. Thanks

**Comment by candidodmv** [comment]
Hi @alexrainman! Thanks for share this project, but how to implements this library in a Xamarin.Forms project?
